# Generated by Django 5.1.7 on 2025-05-05 11:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_image', models.FileField(upload_to='course_images/')),
                ('course_videos', models.FileField(upload_to='course_videos/')),
                ('is_draft', models.BooleanField(default=False)),
            ],
        ),
    ]
