# Generated by Django 5.1.7 on 2025-05-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0002_alter_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrolled',
            field=models.BooleanField(default=False),
        ),
    ]
